FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html consultar_dados.html script.js styles.css /usr/share/nginx/html/
COPY assets /usr/share/nginx/html/assets
COPY fontes /usr/share/nginx/html/fontes
